---
title: "EDA Project"
author: "Sarath Chandra Janapati (20BCE1138), Ashwin K S(20BCE1733)"
date: "03/02/2023"
output:
  pdf_document: default
  html_document: default
---

#Reading Libraries                            
```{r}
library(plyr)  
library(rpart.plot) 
library(caret)
library(gridExtra) 
library(tidyverse) 
library(rsample)
library(e1071) 
library(GGally)
library(data.table)
library(DT)
library(readr)
library(ggplot2)
library(dplyr)
library(tidyr)
library(corrplot)
library(rms)
library(MASS)
library(e1071)
library(ROCR)
library(gplots)
library(pROC)
library(rpart)
library(randomForest)
library(ggpubr)
```

#Reading Data 
```{r}
getwd()
```

```{r}

churn <- read.csv("Churn.csv")

glimpse(churn)
```

#Data Preprocessing
```{r}
sapply(churn, function(x) sum(is.na(x)))
```


```{r}
churn[is.na(churn$TotalCharges),]
```
```{r}
sum(is.na(churn$TotalCharges))/nrow(churn)
```

```{r}
churn_clean <- churn[complete.cases(churn), ]
```


```{r}
churn_clean$SeniorCitizen <- as.factor(mapvalues(churn_clean$SeniorCitizen,
                                          from=c("0","1"),
                                          to=c("No", "Yes")))
```


```{r}
churn_clean$MultipleLines <- as.factor(mapvalues(churn_clean$MultipleLines, 
                                           from=c("No phone service"),
                                           to=c("No")))
```


```{r}
for(i in 10:15){
  churn_clean[,i] <- as.factor(mapvalues(churn_clean[,i],
                                  from= c("No internet service"), to= c("No")))
}
```


```{r}
churn_clean$customerID <- NULL
```


#Data Visualization
```{r}
#1)Demographic data

#Gender plot
p1 <- ggplot(churn_clean, aes(x = gender)) +
  geom_bar(aes(fill = Churn)) +
  geom_text(aes(y = ..count.. -200, 
                label = paste0(round(prop.table(..count..),4) * 100, '%')), 
            stat = 'count', 
            position = position_dodge(.1), 
            size = 3)

#Senior citizen plot
p2 <- ggplot(churn_clean, aes(x = SeniorCitizen)) +
  geom_bar(aes(fill = Churn)) +
  geom_text(aes(y = ..count.. -200, 
                label = paste0(round(prop.table(..count..),4) * 100, '%')), 
            stat = 'count', 
            position = position_dodge(.1), 
            size = 3)

#Partner plot
p3 <- ggplot(churn_clean, aes(x = Partner)) +
  geom_bar(aes(fill = Churn)) +
  geom_text(aes(y = ..count.. -200, 
                label = paste0(round(prop.table(..count..),4) * 100, '%')), 
            stat = 'count', 
            position = position_dodge(.1), 
            size = 3)

#Dependents plot
p4 <- ggplot(churn_clean, aes(x = Dependents)) +
  geom_bar(aes(fill = Churn)) +
  geom_text(aes(y = ..count.. -200, 
                label = paste0(round(prop.table(..count..),4) * 100, '%')), 
            stat = 'count', 
            position = position_dodge(.1), 
            size = 3)

#Plot demographic data within a grid
grid.arrange(p1, p2, p3, p4, ncol=2)
```


```{r}
#2) Offer Services
#Phone service plot
p5 <- ggplot(churn_clean, aes(x = PhoneService)) +
  geom_bar(aes(fill = Churn)) +
  geom_text(aes(y = ..count.. -200, 
                label = paste0(round(prop.table(..count..),4) * 100, '%')), 
            stat = 'count', 
            position = position_dodge(.1), 
            size = 3)

#Multiple phone lines plot
p6 <- ggplot(churn_clean, aes(x = MultipleLines)) +
  geom_bar(aes(fill = Churn)) +
  geom_text(aes(y = ..count.. -200, 
                label = paste0(round(prop.table(..count..),4) * 100, '%')), 
            stat = 'count', 
            position = position_dodge(.1), 
            size = 3)

#Internet service plot
p7 <- ggplot(churn_clean, aes(x = InternetService)) +
  geom_bar(aes(fill = Churn)) +
  geom_text(aes(y = ..count.. -200, 
                label = paste0(round(prop.table(..count..),4) * 100, '%')), 
            stat = 'count', 
            position = position_dodge(.1), 
            size = 3)

#Online security service plot
p8 <- ggplot(churn_clean, aes(x = OnlineSecurity)) +
  geom_bar(aes(fill = Churn)) +
  geom_text(aes(y = ..count.. -200, 
                label = paste0(round(prop.table(..count..),4) * 100, '%')), 
            stat = 'count', 
            position = position_dodge(.1), 
            size = 3)

#Online backup service plot
p9 <- ggplot(churn_clean, aes(x = OnlineBackup)) +
  geom_bar(aes(fill = Churn)) +
  geom_text(aes(y = ..count.. -200, 
                label = paste0(round(prop.table(..count..),4) * 100, '%')), 
            stat = 'count', 
            position = position_dodge(.1), 
            size = 3)

#Device Protection service plot
p10 <- ggplot(churn_clean, aes(x = DeviceProtection)) +
  geom_bar(aes(fill = Churn)) +
  geom_text(aes(y = ..count.. -200, 
                label = paste0(round(prop.table(..count..),4) * 100, '%')), 
            stat = 'count', 
            position = position_dodge(.1), 
            size = 3)

#Tech Support service plot
p11 <- ggplot(churn_clean, aes(x = TechSupport)) +
  geom_bar(aes(fill = Churn)) +
  geom_text(aes(y = ..count.. -200, 
                label = paste0(round(prop.table(..count..),4) * 100, '%')), 
            stat = 'count', 
            position = position_dodge(.1), 
            size = 3)

#Streaming TV service plot
p12 <- ggplot(churn_clean, aes(x = StreamingTV)) +
  geom_bar(aes(fill = Churn)) +
  geom_text(aes(y = ..count.. -200, 
                label = paste0(round(prop.table(..count..),4) * 100, '%')), 
            stat = 'count', 
            position = position_dodge(.1), 
            size = 3)

#Streaming Movies service plot
p13 <- ggplot(churn_clean, aes(x = StreamingMovies)) +
  geom_bar(aes(fill = Churn)) +
  geom_text(aes(y = ..count.. -200, 
                label = paste0(round(prop.table(..count..),4) * 100, '%')), 
            stat = 'count', 
            position = position_dodge(.1), 
            size = 3)

#Plot service data within a grid
grid.arrange(p5, p6, p7,
             p8, p9, p10,
             p11, p12, p13,
             ncol=3)
```


```{r}
#3.For Other Variables
#Contract status plot
p14 <- ggplot(churn_clean, aes(x = Contract)) +
  geom_bar(aes(fill = Churn)) +
  geom_text(aes(y = ..count.. -200, 
                label = paste0(round(prop.table(..count..),4) * 100, '%')), 
            stat = 'count', 
            position = position_dodge(.1), 
            size = 3)

#Paperless billing plot
p15 <- ggplot(churn_clean, aes(x = PaperlessBilling)) +
  geom_bar(aes(fill = Churn)) +
  geom_text(aes(y = ..count.. -200, 
                label = paste0(round(prop.table(..count..),4) * 100, '%')), 
            stat = 'count', 
            position = position_dodge(.1), 
            size = 3)

#Payment method plot
p16 <- ggplot(churn_clean, aes(x = PaymentMethod)) +
  geom_bar(aes(fill = Churn)) +
  geom_text(aes(y = ..count.. -200, 
                label = paste0(round(prop.table(..count..),4) * 100, '%')), 
            stat = 'count', 
            position = position_dodge(.1), 
            size = 3)

#Plot contract data within a grid
grid.arrange(p14, p15, p16, ncol=1)

```


```{r}
#4.Quantitative Variables
#Tenure histogram
p17 <- ggplot(data = churn_clean, aes(tenure, color = Churn))+
  geom_freqpoly(binwidth = 5, size = 1)

#Monthly charges histogram
p18 <- ggplot(data = churn_clean, aes(MonthlyCharges, color = Churn))+
  geom_freqpoly(binwidth = 5, size = 1)

#Total charges histogram
p19 <- ggplot(data = churn_clean, aes(TotalCharges, color = Churn))+
  geom_freqpoly(binwidth = 200, size = 1)

#Plot quantitative data within a grid
grid.arrange(p17, p18, p19, ncol=1)
```


```{r}
#5.Churn:Variable of Interest

p20 <- ggplot(churn_clean, aes(x = Churn)) +
  geom_bar(aes(fill = Churn)) +
  geom_text(aes(y = ..count.. -200, 
                label = paste0(round(prop.table(..count..),4) * 100, '%')), 
            stat = 'count', 
            position = position_dodge(.1), 
            size = 3)
p20
```

#Checking Correlation
```{r}
churn_clean %>%
  dplyr::select (TotalCharges, MonthlyCharges, tenure) %>%
  cor() %>%
  corrplot.mixed(upper = "circle", tl.col = "black", number.cex = 0.7)
```


```{r}
set.seed(56)
split_train_test <- createDataPartition(churn_clean$Churn,p=0.7,list=FALSE)
dtrain<- churn_clean[split_train_test,]
dtest<-  churn_clean[-split_train_test,]

# Remove Total Charges from the training dataset

dtrain <- dtrain[,-19]
dtest <- dtest[,-19]
```

#Modeling
```{r}
#1.Decision Tree analysis
tr_fit <- rpart(Churn ~., data = dtrain, method="class")
rpart.plot(tr_fit)
```

```{r}
tr_prob1 <- predict(tr_fit, dtest)
tr_pred1 <- ifelse(tr_prob1[,2] > 0.5,"Yes","No")
table(Predicted = tr_pred1, Actual = dtest$Churn)
```


```{r}
tr_prob2 <- predict(tr_fit, dtrain)
tr_pred2 <- ifelse(tr_prob2[,2] > 0.5,"Yes","No")
tr_tab1 <- table(Predicted = tr_pred2, Actual = dtrain$Churn)
tr_tab2 <- table(Predicted = tr_pred1, Actual = dtest$Churn)
```


```{r}
# Train
confusionMatrix(
  as.factor(tr_pred2),
  as.factor(dtrain$Churn),
  positive = "Yes" 
)
```


```{r}
# Test
confusionMatrix(
as.factor(tr_pred1),
  as.factor(dtest$Churn),
  positive = "Yes" 
)
```


```{r}
tr_acc <- sum(diag(tr_tab2))/sum(tr_tab2)
tr_acc
```


```{r}
#2.Random Forest
df = read.csv("Churn.csv")
head(df)

# Installing the package
#install.packages("caTools") # For Logistic regression
#install.packages("ROCR")	 # For ROC curve to evaluate model

# Loading package
library(caTools)
library(ROCR)
library(caret)
df <- na.omit(df)
df <- df[3:21]
df$Churn <- as.factor(df$Churn)
head(df)
# Splitting dataset
split <- sample.split(df, SplitRatio = 0.7)
split

train_reg <- subset(df, split == "TRUE")
test_reg <- subset(df, split == "FALSE")


#Random Forest Model

#install.packages("randomForest")  # For implementing random forest algorithm
# Loading package
library(randomForest)

head(train_reg)
dim(train_reg)
dim(train_reg)

head(test_reg)
dim(test_reg)

as.factor(df$Churn)

# Fitting Random Forest to the train dataset
set.seed(120)  # Setting seed
classifier_RF = randomForest(Churn~.,
                             data = train_reg,
                             ntree = 500)

classifier_RF

# Predicting the Test set results
y_pred = predict(classifier_RF, newdata = test_reg)
y_pred
confusionMatrix(y_pred,as.factor(test_reg$Churn))

# Plotting model
plot(classifier_RF)

# Importance plot
importance(classifier_RF)

# Variable importance plot
varImpPlot(classifier_RF)













```





```{r}
#Logistic Regression
# Installing the package
#install.packages("caTools") # For Logistic regression
#install.packages("ROCR")	 # For ROC curve to evaluate model

# Loading package
library(caTools)
library(ROCR)

df <- read.csv("Churn.csv")
df$Churn <- as.factor(df$Churn)
# Splitting dataset
split <- sample.split(df, SplitRatio = 0.7)
split

train_reg <- subset(df, split == "TRUE")
test_reg <- subset(df, split == "FALSE")







```

```{r}
# Training model
logistic_model <- glm(Churn ~ .,
                      data = train_reg,
                      family = "binomial")
logistic_model

# Summary
summary(logistic_model)
```



```{r}
# Predict test data based on model
predict_reg <- predict(logistic_model,
                       test_reg, type = "response")
predict_reg

# Changing probabilities
predict_reg <- ifelse(predict_reg >0.5, 1, 0)
predict_reg<-as.factor(predict_reg)
# Evaluating model accuracy
# using confusion matrix
table(test_reg$Churn, predict_reg)

```


```{r}
# lr_prob2 <- predict(lr_fit, dtrain, type="response")
# lr_pred2 <- ifelse(lr_prob2 > 0.5,"Yes","No")
# lr_tab1 <- table(Predicted = lr_pred2, Actual = dtrain$Churn)
# lr_tab2 <- table(Predicted = lr_pred1, Actual = dtest$Churn)
```


```{r}

library(caret)
confusionMatrix(predict_reg,as.factor(test_reg$Churn))
```


`

#Data Visualization based on Models
```{r}
p21 <- ggplot(churn_clean, aes(x = Contract, fill = Churn)) +
  geom_bar() +
  geom_text(aes(y = ..count.. -200, 
                label = paste0(round(prop.table(..count..),4) * 100, '%')), 
            stat = 'count', 
            position = position_dodge(.1), 
            size = 3) +
  labs(title="Churn rate by contract status")

p21
```


```{r}
p22 <- ggplot(churn_clean, aes(x = InternetService, fill = Churn)) +
  geom_bar() +
  geom_text(aes(y = ..count.. -200, 
                label = paste0(round(prop.table(..count..),4) * 100, '%')), 
            stat = 'count', 
            position = position_dodge(.1), 
            size = 3) +
  labs(title="Churn rate by internet service status")

p22
```


```{r}
p23 <- ggplot(churn_clean, aes(x = tenure, fill = Churn)) +
  geom_histogram(binwidth = 1) +
  labs(x = "Months",
       title = "Churn rate by tenure")
p23
```

```{r}
p24 <- ggplot(churn_clean, aes(x = TotalCharges, fill = Churn)) +
  geom_histogram(binwidth = 100) +
  labs(x = "Dollars (binwidth=100)",
       title = "Churn rate by tenure")
p24
```

